#pragma once
#include <stdint.h>		// uint64_t
#include <intrin.h>

typedef struct Board Board;
typedef signed short Color;

enum Piece { wpawn, bpawn, wrook, brook, wbishop, bbishop, wknight, bknight, wqueen, bqueen, wking, bking, notype };

#define MAX_PIECES_OF_ONE_TYPE				10
#define MAX_POSSIBLE_MOVES					256
#define MAX_MOVES_WITHOUT_DOING_ANYTHING	50
#define LEFT				0
#define RIGHT				0x1
#define W_ARRAY				0
#define B_ARRAY				0x1
#define WHITE				1
#define BLACK				-1
#define NORTH				0x1
#define SOUTH				0x0
#define BOARD_SIZE			0x8
#define NE_SHIFT_B			0x7
#define NW_SHIFT_B			0x9
#define SE_SHIFT_B			0x9
#define SW_SHIFT_B			0x7
#define LAST_BIT			0x8000000000000000
#define LAST_BIT_POS		0x3F
#define SIZEOF_U64_TIMES_8	64 // 8*sizeof(uint64_t)
#define CONSTS_SIZE			65 // sizeof_u64_times_8 + 1 (0 at the begining)
#define CLZ(X)				((unsigned)__lzcnt64(X))	// returns 1 --> 63, 0 --> 64
#define CTZ(X)				((unsigned)_tzcnt_u64(X))
#define POPCNT(X)			((unsigned)__popcnt64(X))
#define CTZ_ARR(X)			(((unsigned)CTZ(X) + 1) % CONSTS_SIZE)	// returns 1 --> 0, 0 --> 64
#define LOG2(X)				(SIZEOF_U64_TIMES_8 - CLZ(X))
#define GET_OPPONENT(X)			((signed) (-1 * X))
#define PLAYER_JUST_MOVED(X) 	((signed) (-1 * X))
#define I_SIZE				4 // sizeof(int)
#define HALF_BOARD_SIZE		0x30

#define bit_columnH		0x101010101010101
#define bit_line		0xFF
#define r_start_w		0x81
#define b_start_w		0x24
#define k_start_w		0x42
#define q_start_w		0x10
#define king_start_w	0x8
extern const uint64_t w_start[6];

// CONST for roque
extern const uint64_t needs_to_be_empty[2][2];
extern const uint64_t not_be_attacked[2][2];

// CONSTS generated by the other project "CreateConsts"
// They are numbers that represent the cases attacked by a bishop or a rook in all the different places possible
extern const uint64_t attacked_by_bishops_NE[CONSTS_SIZE];
extern const uint64_t attacked_by_bishops_NW[CONSTS_SIZE];
extern const uint64_t attacked_by_bishops_SE[CONSTS_SIZE];
extern const uint64_t attacked_by_bishops_SW[CONSTS_SIZE];
extern const uint64_t attacked_by_rooks_N[CONSTS_SIZE];
extern const uint64_t attacked_by_rooks_W[CONSTS_SIZE];
extern const uint64_t attacked_by_rooks_E[CONSTS_SIZE];
extern const uint64_t attacked_by_rooks_S[CONSTS_SIZE];